### ISSUE TITLE
ClientAPIRequest 这个类 是哪里来的？ 编译时总找不到。

### ISSUE THREAD

**Issue by ifcheung2012** [Ronaltn/BAH.BOS.WebAPI.Client#1]
代码不错，如果能把解决方案.sln也commit上来，就好了 ，vs 第一次玩  ，不熟悉。

**Comment by Ronaltn** [comment]
ClientAPIRequest是net35工程特有的，即通过net35本身的Http对象来发起请求和接收结果。
net35的sln就位于该目录的根目录，请用Visual Studio 2008打开。
